### ISSUE TITLE
Wrong command for open telnet

### ISSUE THREAD

**Issue by Anzic23** [lasthead0/ioBroker.xiaomi-gateway3#11]
**Describe the bug**  
I added a gateway, I try to open telnet using the built-in commands, it does not work. Ours is a similar command on the Internet, but with a difference in the id number, I tried to enter it, and hooray, the telnet opened.
**To Reproduce**  
1. enter command from example {"id":**0**,"method": .....
2. see error
**Expected behavior**  
Add or fix telnet open method
{"id":**123**,"method": ......

**Versions:**  
 - Adapter version: 0.3.4
 - JS-Controller version: 4.0.15
 - Node version: v12.22.5
 - Operating system: debian
 - GW firmware version 1.4.5_0012

**Additional context**

**Comment by lasthead0** [comment]
This `id` is id of command and This `id` is id of command but not of payload. There is doesn't matter what id because it will be replaced with random.
Also we can see "You may need to change id." at this page https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e02270

Besides i need to see error, to undersand what happend exactly.
For now i will left this as it is.
